services:
  mfa-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: mfa-aligner-service:latest
    container_name: mfa_aligner_api
    ports:
      - "8001:8001"
    volumes:
      - mfa_data:/home/mfauser/Documents/MFA
      - ./app:/app
    restart: unless-stopped

volumes:
  mfa_data:
    name: mfa_data_storage
